/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/nao/catkin_ws/src/unb_robocup/srv/SPLMsg.srv
 *
 */


#ifndef UNB_ROBOCUP_MESSAGE_SPLMSGRESPONSE_H
#define UNB_ROBOCUP_MESSAGE_SPLMSGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace unb_robocup
{
template <class ContainerAllocator>
struct SPLMsgResponse_
{
  typedef SPLMsgResponse_<ContainerAllocator> Type;

  SPLMsgResponse_()
    : playerNum(0)
    , teamColor(0)
    , fallen(0)
    , pose()
    , walkingTo()
    , shootingTo()
    , ballAge(0)
    , ball()
    , ballVel()
    , intention(0)
    , numOfDataBytes(0)  {
      pose.assign(0.0);

      walkingTo.assign(0.0);

      shootingTo.assign(0.0);

      ball.assign(0.0);

      ballVel.assign(0.0);
  }
  SPLMsgResponse_(const ContainerAllocator& _alloc)
    : playerNum(0)
    , teamColor(0)
    , fallen(0)
    , pose()
    , walkingTo()
    , shootingTo()
    , ballAge(0)
    , ball()
    , ballVel()
    , intention(0)
    , numOfDataBytes(0)  {
      pose.assign(0.0);

      walkingTo.assign(0.0);

      shootingTo.assign(0.0);

      ball.assign(0.0);

      ballVel.assign(0.0);
  }



   typedef int8_t _playerNum_type;
  _playerNum_type playerNum;

   typedef int8_t _teamColor_type;
  _teamColor_type teamColor;

   typedef int8_t _fallen_type;
  _fallen_type fallen;

   typedef boost::array<float, 3>  _pose_type;
  _pose_type pose;

   typedef boost::array<float, 2>  _walkingTo_type;
  _walkingTo_type walkingTo;

   typedef boost::array<float, 2>  _shootingTo_type;
  _shootingTo_type shootingTo;

   typedef int32_t _ballAge_type;
  _ballAge_type ballAge;

   typedef boost::array<float, 2>  _ball_type;
  _ball_type ball;

   typedef boost::array<float, 2>  _ballVel_type;
  _ballVel_type ballVel;

   typedef int16_t _intention_type;
  _intention_type intention;

   typedef int16_t _numOfDataBytes_type;
  _numOfDataBytes_type numOfDataBytes;




  typedef boost::shared_ptr< ::unb_robocup::SPLMsgResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::unb_robocup::SPLMsgResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct SPLMsgResponse_

typedef ::unb_robocup::SPLMsgResponse_<std::allocator<void> > SPLMsgResponse;

typedef boost::shared_ptr< ::unb_robocup::SPLMsgResponse > SPLMsgResponsePtr;
typedef boost::shared_ptr< ::unb_robocup::SPLMsgResponse const> SPLMsgResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::unb_robocup::SPLMsgResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::unb_robocup::SPLMsgResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace unb_robocup

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/openrobots/share/sensor_msgs/msg'], 'std_msgs': ['/opt/openrobots/share/std_msgs/msg'], 'geometry_msgs': ['/opt/openrobots/share/geometry_msgs/msg'], 'unb_robocup': ['/home/nao/catkin_ws/src/unb_robocup/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::unb_robocup::SPLMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unb_robocup::SPLMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unb_robocup::SPLMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unb_robocup::SPLMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unb_robocup::SPLMsgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unb_robocup::SPLMsgResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::unb_robocup::SPLMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a61e78d7087f8ec58acadd5ee3b8e4e6";
  }

  static const char* value(const ::unb_robocup::SPLMsgResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa61e78d7087f8ec5ULL;
  static const uint64_t static_value2 = 0x8acadd5ee3b8e4e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::unb_robocup::SPLMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "unb_robocup/SPLMsgResponse";
  }

  static const char* value(const ::unb_robocup::SPLMsgResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::unb_robocup::SPLMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 playerNum\n\
int8 teamColor\n\
int8 fallen\n\
float32[3] pose\n\
float32[2] walkingTo\n\
float32[2] shootingTo\n\
int32 ballAge\n\
float32[2] ball\n\
float32[2] ballVel\n\
int16 intention\n\
int16 numOfDataBytes\n\
\n\
\n\
";
  }

  static const char* value(const ::unb_robocup::SPLMsgResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::unb_robocup::SPLMsgResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.playerNum);
      stream.next(m.teamColor);
      stream.next(m.fallen);
      stream.next(m.pose);
      stream.next(m.walkingTo);
      stream.next(m.shootingTo);
      stream.next(m.ballAge);
      stream.next(m.ball);
      stream.next(m.ballVel);
      stream.next(m.intention);
      stream.next(m.numOfDataBytes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SPLMsgResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::unb_robocup::SPLMsgResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::unb_robocup::SPLMsgResponse_<ContainerAllocator>& v)
  {
    s << indent << "playerNum: ";
    Printer<int8_t>::stream(s, indent + "  ", v.playerNum);
    s << indent << "teamColor: ";
    Printer<int8_t>::stream(s, indent + "  ", v.teamColor);
    s << indent << "fallen: ";
    Printer<int8_t>::stream(s, indent + "  ", v.fallen);
    s << indent << "pose[]" << std::endl;
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      s << indent << "  pose[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pose[i]);
    }
    s << indent << "walkingTo[]" << std::endl;
    for (size_t i = 0; i < v.walkingTo.size(); ++i)
    {
      s << indent << "  walkingTo[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.walkingTo[i]);
    }
    s << indent << "shootingTo[]" << std::endl;
    for (size_t i = 0; i < v.shootingTo.size(); ++i)
    {
      s << indent << "  shootingTo[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.shootingTo[i]);
    }
    s << indent << "ballAge: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ballAge);
    s << indent << "ball[]" << std::endl;
    for (size_t i = 0; i < v.ball.size(); ++i)
    {
      s << indent << "  ball[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.ball[i]);
    }
    s << indent << "ballVel[]" << std::endl;
    for (size_t i = 0; i < v.ballVel.size(); ++i)
    {
      s << indent << "  ballVel[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.ballVel[i]);
    }
    s << indent << "intention: ";
    Printer<int16_t>::stream(s, indent + "  ", v.intention);
    s << indent << "numOfDataBytes: ";
    Printer<int16_t>::stream(s, indent + "  ", v.numOfDataBytes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNB_ROBOCUP_MESSAGE_SPLMSGRESPONSE_H
