(cl:in-package unb_robocup-srv)
(cl:export '(PLAYERNUM-VAL
          PLAYERNUM
          TEAMCOLOR-VAL
          TEAMCOLOR
          FALLEN-VAL
          FALLEN
          POSE-VAL
          POSE
          WALKINGTO-VAL
          WALKINGTO
          SHOOTINGTO-VAL
          SHOOTINGTO
          BALLAGE-VAL
          BALLAGE
          BALL-VAL
          BALL
          BALLVEL-VAL
          BALLVEL
          INTENTION-VAL
          INTENTION
          NUMOFDATABYTES-VAL
          NUMOFDATABYTES
          PLAYERNUM-VAL
          PLAYERNUM
          TEAMCOLOR-VAL
          TEAMCOLOR
          FALLEN-VAL
          FALLEN
          POSE-VAL
          POSE
          WALKINGTO-VAL
          WALKINGTO
          SHOOTINGTO-VAL
          SHOOTINGTO
          BALLAGE-VAL
          BALLAGE
          BALL-VAL
          BALL
          BALLVEL-VAL
          BALLVEL
          INTENTION-VAL
          INTENTION
          NUMOFDATABYTES-VAL
          NUMOFDATABYTES
))